source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

pod 'Alamofire'
pod 'Starscream'
pod 'SwiftyJSON'
pod 'SlackTextViewController'
pod 'FBSDKCoreKit'
pod 'FBSDKLoginKit'

target 'HearstKit_Example', :exclusive => true do
  pod 'HearstKit', :path => '../'
end

target 'HearstKit_Tests', :exclusive => true do
  pod 'HearstKit', :path => '../'
end
